<a href="https://colab.research.google.com/github/NDOWAH/project/blob/master/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
numbers = [-25.23,-13.897,-9, 28,36,46,49,53,57.43,67.33,70.45]

The code below generates output base on given inputs and given algorithm

In [8]:
 output = []
def generate_val():
  for number in numbers:
    val = 6.25*number + 30 
    output.append(val)
  return "numbers: {}, output: {}".format(numbers,output)

In [9]:
generate_val()

'numbers: [-25.23, -13.897, -9, 28, 36, 46, 49, 53, 57.43, 67.33, 70.45], output: [-127.6875, -56.85625, -26.25, 205.0, 255.0, 317.5, 336.25, 361.25, 388.9375, 450.8125, 470.3125]'

# The task here is to use ML techniques to find m and c in the equation : y = mx + c.
# Given the inputset and the outputset generated by the code above.

In [10]:

import tensorflow as tf
import numpy as np

In [12]:
input_arr = np.array(numbers,dtype=float)
output_arr = np.array(output,dtype=float)

In [32]:
for i,number in enumerate(numbers):
      print("%s is mapped to %s"%(number,output[i]))

-25.23 is mapped to -127.6875
-13.897 is mapped to -56.85625
-9 is mapped to -26.25
28 is mapped to 205.0
36 is mapped to 255.0
46 is mapped to 317.5
49 is mapped to 336.25
53 is mapped to 361.25
57.43 is mapped to 388.9375
67.33 is mapped to 450.8125
70.45 is mapped to 470.3125

# Creating and assembling the module.

In [39]:
model= tf.keras.Sequential([tf.keras.layers.Dense(units=1, input_shape = [1])])

In [ ]:
c

# Compiling the model.

In [55]:
model.compile(loss="means_square_error",optimizer=tf.keras.optimizers.Adam(0.1))

#Training the Model